--Q1. What is the total revenue generated by male vs. female customers?
SELECT gender,sum(purchase_amount) AS revenue
FROM customer_behavior 
GROUP BY gender

--Q2. Which customers used a discount but still spent more than the average purchase amount? 
SELECT * FROM customer_behavior LIMIT 5

SELECT customer_id, purchase_amount
FROM customer_behavior 
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM customer_behavior)

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, round(avg(review_rating::numeric),2) as avg_rating
FROM customer_behavior
GROUP BY item_purchased
ORDER BY avg_rating DESC 
LIMIT 5

--Q4. Compare the average Purchase Amounts between Standard and Express Shipping. 
SELECT shipping_type, round(AVG(purchase_amount)::numeric,2) AS avg_amount
FROM customer_behavior
WHERE shipping_type IN ('Express', 'Standard')
GROUP BY shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT 
	subscription_status, 
	COUNT(customer_id) AS customer_count,
	round(AVG(purchase_amount)::numeric,2) AS avg_spend,
	SUM(purchase_amount) AS total_revenue	
FROM customer_behavior
GROUP BY subscription_status 

SELECT * FROM customer_behavior LIMIT 5

--Q6. Which 5 products have the highest percentage of purchases with discounts applied
--CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END signifies that code is summing 1's everytime the CASE is Yes.
--The above part divided by total count gives us the % of purchase where discount is applied

SELECT item_purchased, 
ROUND(100.0 * SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*),2) AS percent_purchase
FROM customer_behavior
GROUP BY item_purchased
ORDER BY percent_purchase DESC
LIMIT 5;

--Q7. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
--Reframe Q as, how many total purchases are there if subscription is Yes or No. This will tell us the behavior of whether they 
--will rebuy or not if there is a subscription
SELECT * FROM customer_behavior LIMIT 5

SELECT subscription_status, COUNT(customer_id) AS repeat_purchase
FROM customer_behavior
WHERE purchase_frequency_days > 5
GROUP BY subscription_status

--Q8. What is the revenue contribution of each age group? 
SELECT * FROM customer_behavior LIMIT 5

SELECT age_group, SUM(purchase_amount) as revenue
FROM customer_behavior
GROUP BY age_group
ORDER BY revenue DESC

--Q9. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
--and show the count of each segment.
WITH customer_types AS 
(
	SELECT customer_id, previous_purchases,
	CASE 
		WHEN previous_purchases = 1 THEN 'New'
		WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
		ELSE 'Loyal'
		END AS customer_segment
	FROM customer_behavior --This gives us the 3 segments of customer types based on customer ID and previous_purchase
)
SELECT customer_segment, count(customer_id) AS total_count
FROM customer_types
GROUP BY customer_segment
ORDER BY total_count DESC

SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_behavior
    GROUP BY category, item_purchased

WITH item_counts AS (
    SELECT category,
           item_purchased,
           COUNT(customer_id) AS total_orders,
           ROW_NUMBER() OVER (PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
    FROM customer_behavior
    GROUP BY category, item_purchased
)
SELECT item_rank,category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <=3;
